# Generated by Django 6.0.3 on 2026-05-13 09:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BRRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('br_number', models.CharField(db_index=True, help_text='Unique BR number from auction floor', max_length=30, unique=True, verbose_name='BR Number')),
                ('sale_date', models.DateField(db_index=True, verbose_name='Sale Date')),
                ('received_date', models.DateTimeField(db_index=True, help_text='Timestamp when bales physically arrived', verbose_name='Date Received at TSF')),
                ('total_bales', models.PositiveIntegerField(verbose_name='Total Bales on BR')),
                ('total_mass', models.DecimalField(decimal_places=2, help_text='Total mass in kg from BR document', max_digits=10, verbose_name='Total Mass')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(help_text='BR Clerk who recorded this BR', limit_choices_to={'groups__name': 'BR Clerk'}, on_delete=django.db.models.deletion.PROTECT, related_name='br_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BR Record',
                'verbose_name_plural': 'BR Records',
                'ordering': ['-sale_date', '-br_number'],
            },
        ),
        migrations.CreateModel(
            name='Bale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, help_text='Physical barcode on bale', max_length=50, verbose_name='Barcode')),
                ('grower_no', models.CharField(db_index=True, max_length=20, verbose_name='Grower Number')),
                ('lot_no', models.CharField(db_index=True, max_length=20, verbose_name='Lot Number')),
                ('mass', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Mass')),
                ('reason', models.CharField(choices=[('GOOD', 'Good Condition'), ('OVERWEIGHT', 'Overweight >100kg'), ('UNDERWEIGHT', 'Underweight <40kg'), ('WET', 'Wet/Damp'), ('MOULDY', 'Mouldy/Musty'), ('DAMAGED', 'Physically Damaged'), ('MIXED', 'Mixed Grades'), ('INFESTED', 'Pest Infested'), ('OTHER', 'Other - See Notes')], db_index=True, default='GOOD', max_length=15, verbose_name='Condition / Reason')),
                ('reason_notes', models.CharField(blank=True, max_length=200, verbose_name='Reason Notes')),
                ('floor', models.CharField(choices=[('A', 'Floor A'), ('B', 'Floor B'), ('C', 'Floor C'), ('D', 'Floor D')], default='A', max_length=1, verbose_name='Floor')),
                ('stack', models.CharField(max_length=15, verbose_name='Stack')),
                ('row', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(34)], verbose_name='Row')),
                ('side', models.CharField(choices=[('L', 'Left'), ('R', 'Right')], default='L', max_length=1, verbose_name='Side')),
                ('level', models.PositiveSmallIntegerField(help_text='Vertical position in stack, 1 is bottom', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Level')),
                ('status', models.CharField(choices=[('InStock', 'In Stock - Available for Collection'), ('Reserved', 'Reserved - Awaiting Collection'), ('Collected', 'Collected by Farmer'), ('Removed', 'Removed - Damaged/Discarded')], db_index=True, default='InStock', max_length=15, verbose_name='Status')),
                ('date_received', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Date Received')),
                ('date_scanned', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date Scanned')),
                ('date_collected', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Date Collected')),
                ('collected_by', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Collection Dept'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bales_collected', to=settings.AUTH_USER_MODEL)),
                ('scanned_by', models.ForeignKey(limit_choices_to={'groups__name': 'BR Clerk'}, on_delete=django.db.models.deletion.PROTECT, related_name='bales_scanned', to=settings.AUTH_USER_MODEL)),
                ('br_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bales', to='tracker.brrecord')),
            ],
            options={
                'verbose_name': 'Bale',
                'verbose_name_plural': 'Bales',
                'ordering': ['floor', 'stack', 'row', 'side', 'level'],
            },
        ),
        migrations.CreateModel(
            name='BaleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=15)),
                ('old_location', models.CharField(blank=True, max_length=100)),
                ('new_status', models.CharField(max_length=15)),
                ('new_location', models.CharField(blank=True, max_length=100)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('bale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tracker.bale')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bale History',
                'verbose_name_plural': 'Bale History',
                'ordering': ['-changed_at'],
                'get_latest_by': 'changed_at',
                'indexes': [models.Index(fields=['bale', 'changed_at'], name='history_bale_time_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='brrecord',
            index=models.Index(fields=['sale_date', 'received_date'], name='br_date_idx'),
        ),
        migrations.AddIndex(
            model_name='bale',
            index=models.Index(fields=['status', 'floor', 'stack', 'row', 'side'], name='bale_location_idx'),
        ),
        migrations.AddIndex(
            model_name='bale',
            index=models.Index(fields=['br_record', 'date_scanned'], name='bale_br_date_idx'),
        ),
        migrations.AddIndex(
            model_name='bale',
            index=models.Index(fields=['grower_no', 'lot_no', 'status'], name='bale_grower_idx'),
        ),
        migrations.AddIndex(
            model_name='bale',
            index=models.Index(fields=['date_scanned'], name='bale_scanned_idx'),
        ),
        migrations.AddConstraint(
            model_name='bale',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'InStock')), fields=('floor', 'stack', 'row', 'side', 'level', 'status'), name='unique_slot_in_stock'),
        ),
        migrations.AddConstraint(
            model_name='bale',
            constraint=models.UniqueConstraint(fields=('br_record', 'barcode'), name='unique_bale_per_br'),
        ),
    ]
