# Generated by Django 6.0.3 on 2026-05-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bale',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Physical barcode on bale', max_length=50, verbose_name='Barcode'),
        ),
    ]
