# Generated by Django 6.0.3 on 2026-05-19 04:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_bale_barcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bale',
            options={'ordering': ['floor', 'row', 'side', 'level']},
        ),
        migrations.AlterModelOptions(
            name='balehistory',
            options={'ordering': ['-changed_at']},
        ),
        migrations.AlterModelOptions(
            name='brrecord',
            options={'ordering': ['-sale_date', '-br_number']},
        ),
        migrations.RemoveConstraint(
            model_name='bale',
            name='unique_slot_in_stock',
        ),
        migrations.RemoveConstraint(
            model_name='bale',
            name='unique_bale_per_br',
        ),
        migrations.RemoveIndex(
            model_name='bale',
            name='bale_location_idx',
        ),
        migrations.RemoveIndex(
            model_name='bale',
            name='bale_scanned_idx',
        ),
        migrations.AlterField(
            model_name='bale',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Barcode'),
        ),
        migrations.AlterField(
            model_name='bale',
            name='br_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bales', to='tracker.brrecord'),
        ),
        migrations.AlterField(
            model_name='bale',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bales_collected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bale',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, help_text='Vertical position in stack, 1 is bottom', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='bale',
            name='reason',
            field=models.CharField(choices=[('RR', 'Over/Under Weight'), ('MR', 'Mixed Hand'), ('LR', 'Mouldy'), ('BGRW', 'Wet'), ('OR', 'Hot'), ('WR', 'Wrong Hessian'), ('DR', 'Diesel'), ('NE', 'Nesting'), ('GOOD', 'Good Condition')], db_index=True, default='GOOD', max_length=10, verbose_name='Condition / Reason'),
        ),
        migrations.AlterField(
            model_name='bale',
            name='row',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Row'),
        ),
        migrations.AlterField(
            model_name='bale',
            name='scanned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bales_scanned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='balehistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='brrecord',
            name='br_number',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='BR Number'),
        ),
        migrations.AlterField(
            model_name='brrecord',
            name='received_date',
            field=models.DateTimeField(db_index=True, verbose_name='Date Received at TSF'),
        ),
        migrations.AlterField(
            model_name='brrecord',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='br_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='brrecord',
            name='total_bales',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Bales on BR'),
        ),
        migrations.AlterField(
            model_name='brrecord',
            name='total_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Mass'),
        ),
        migrations.AddIndex(
            model_name='bale',
            index=models.Index(fields=['status', 'floor', 'row', 'side', 'level'], name='bale_location_idx'),
        ),
        migrations.AddConstraint(
            model_name='bale',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'InStock')), fields=('floor', 'row', 'side', 'level', 'status'), name='unique_slot_in_stock'),
        ),
        migrations.AddConstraint(
            model_name='bale',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode', ''), _negated=True), fields=('br_record', 'barcode'), name='unique_bale_per_br'),
        ),
        migrations.RemoveField(
            model_name='bale',
            name='stack',
        ),
    ]
